"""Neutral file constants shared by API models and file-scope helpers."""

SUPPORTED_EXTENSIONS = {".xlsx", ".xls", ".docx", ".pptx"}
SUPPORTED_EXTENSIONS_LABEL = ".xlsx, .xls, .docx, .pptx"

DEFAULT_EXCLUDED_FOLDER_NAMES = [
    ".git",
    ".svn",
    ".hg",
    "node_modules",
    "bower_components",
    "vendor",
    "venv",
    ".venv",
    "env",
    ".tox",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".cache",
    "dist",
    "build",
    "out",
    "target",
    "bin",
    "obj",
    ".next",
    ".nuxt",
    ".gradle",
    ".m2",
    ".cargo",
    ".rustup",
    ".vscode",
    ".idea",
    ".vs",
    "AppData",
    "Library",
    "Application Support",
    ".codex",
    ".claude",
    ".omx",
    ".omc",
]
