export { buildExcelGridFocuses, ExcelCheckResult, ExcelDiffGridModal } from './excelResult'
export { CompareMetadataWarnings } from './warnings'
export { HistoryTransitions } from './historyTransitions'
export { GroupTimeline } from './GroupTimeline'
export { WordCheckResult } from './wordResult'
export { PptCheckResult } from './pptResult'
export { DiffPanel } from './diffPanel'
export type { CompareSelection, CompareSlot, HistoryDiffState } from './GroupTimeline'
export type { ExcelGridModalState, HistoryTransition, HistoryTransitionStatus } from './types'
