export type TutorialStep =
  | 'example-folder'
  | 'document-refresh'
  | 'search'
  | 'search-results'
  | 'search-review'
  | 'version-ppt'
  | 'version-ppt-review'
  | 'version-excel'
  | 'version-excel-review'
  | 'excel-table'
  | 'excel-table-review'
  | 'done'

export const EXAMPLE_SEARCH_QUERY = '프로젝트'
export const EXAMPLE_PPT_QUERY = '프로젝트상태'
export const EXAMPLE_EXCEL_QUERY = '사업예산'
